### ISSUE TITLE
Wierd Scroll Bar Glitch in Unit test-class generator

### ISSUE THREAD

**Issue by DarioArena87** [junit-tools-team/junit-tools#4] opened 2017-10-12 13:34 UTC
Hi everyone,
i don't really know if it's junit-tools' fault but when theming is enabled in Eclipse, Scrollbars in "methods" box in in Unit test-class generator (the window tha opens when CTRL+< are pressed) strangely glitches between "classics" toolbars and themed ones.

**Comment by robertstreng** [comment] 2017-10-12 16:01
Thank you for the information, we will analyse the issue

**Comment by robertstreng** [comment] 2017-10-13 14:24
It works correct on windows and macs with different themes. It is obviously a problem of the theme. Did you try another theme? What for a theme have you activated?

**Comment by DarioArena87** [comment] 2017-10-14 14:04
Hi, i tried the default theme of Eclipse Oxygen and the "Clean Sheet" theme. With the classic theme (the "Win98" style) it works fine.

**Comment by robertstreng** [comment] 2018-03-13 10:19
We have tested a lot of themes (clean sheet, win98 style too) on windows and macs but we cannot reproducethe problem. I will close this issue because we are using only default swt controls and the cause of the problem is obviously not the implementation of JUnit-Tools.

**Closed as completed by robertstreng** 2018-03-13 10:19 UTC
